-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd [[highlight clear]]

local highlight = function(group, bg, fg, attr)
  fg = fg and 'guifg=' .. fg or ''
  bg = bg and 'guibg=' .. bg or ''
  attr = attr and 'gui=' .. attr or ''

  vim.api.nvim_command('highlight ' .. group .. ' ' .. fg .. ' ' .. bg .. ' ' .. attr)
end

local link = function(target, group)
  vim.api.nvim_command('highlight! link ' .. target .. ' ' .. group)
end

local Color17 = '#b1b494'
local Color1 = '#00A3CC'
local Color9 = '#ecf0c1'
local Color5 = '#CE6F8F'
local Color16 = '#16172d'
local Color11 = '#272c42'
local Color2 = '#F2CE00'
local Color10 = '#0f111b'
local Color14 = '#30365F'
local Color8 = '#1b1c36'
local Color6 = '#D0D0FF'
local Color12 = '#23423b'
local Color13 = '#7b230d'
local Color7 = '#5CCC96'
local Color3 = '#ECF0C1'
local Color4 = '#7A5CCC'
local Color15 = '#686f9a'
local Color0 = '#535f97'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('Identifier', nil, Color3, nil)
highlight('Keyword', nil, Color4, 'italic')
highlight('Operator', nil, Color5, 'italic')
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Type', nil, Color6, 'italic')
highlight('Type', nil, Color2, nil)
highlight('Function', nil, Color7, nil)
highlight('Error', nil, Color3, nil)
highlight('StatusLine', Color9, Color8, nil)
highlight('WildMenu', Color10, Color9, nil)
highlight('Pmenu', Color10, Color9, nil)
highlight('PmenuSel', Color9, Color11, nil)
highlight('PmenuThumb', Color10, Color9, nil)
highlight('DiffAdd', Color12, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color10, Color9, nil)
highlight('Visual', Color14, nil, nil)
highlight('CursorLine', Color14, nil, nil)
highlight('ColorColumn', Color14, nil, nil)
highlight('SignColumn', Color10, nil, nil)
highlight('LineNr', nil, Color15, nil)
highlight('TabLine', Color16, Color17, nil)
highlight('TabLineSel', Color9, Color11, nil)
highlight('TabLineFill', Color16, Color17, nil)
highlight('TSPunctDelimiter', nil, Color9, nil)

link('Conditional', 'Operator')
link('TSComment', 'Comment')
link('TSRepeat', 'Repeat')
link('TSString', 'String')
link('TSField', 'Constant')
link('TSFloat', 'Number')
link('TSTagDelimiter', 'Type')
link('TSFunction', 'Function')
link('TSParameter', 'Constant')
link('TSParameterReference', 'TSParameter')
link('NonText', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('TSOperator', 'Operator')
link('TSKeyword', 'Keyword')
link('TSConstant', 'Constant')
link('Operator', 'Keyword')
link('TSConditional', 'Conditional')
link('TSPunctBracket', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Folded', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Macro', 'Function')
link('Whitespace', 'Comment')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('TSNumber', 'Number')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('CursorLineNr', 'Identifier')
link('TSType', 'Type')

vim.g.colors_name = "spaceduck"
